project_id = "pccssnlomqaraygclpzw"

[functions.generate-image]
enabled = true
verify_jwt = false

[functions.pusher-trigger]
enabled = true
verify_jwt = true
import_map = "./functions/pusher-trigger/deno.json"
entrypoint = "./functions/pusher-trigger/index.ts"

[functions.admin-vendor-payouts]
enabled = true
verify_jwt = false

[functions.get-users]
enabled = true
verify_jwt = false
